# Generated by Django 2.2.6 on 2019-11-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
