# Generated by Django 2.2.6 on 2019-11-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20191103_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dieccion',
            new_name='direccion',
        ),
    ]
